env:
  global:
    - CC_TEST_REPORTER_ID=9c3a4c12da21071eb7199ef9c539eb45dd916557e2b99b333961e7d3ded5d01f
language: node_js
node_js: '10'
script:
  - npm run build
deploy:
  on:
    branch: develop
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: app.staging.docket.fyi
  region: us-west-2
  acl: public_read
  local_dir: build
  skip_cleanup: true
notifications:
  slack:
    secure: gc/gJXAVvP601rKwPxaAwoqcwc5o3Yp8aNxcmD3cl4sEt9+Uv3vafoK6/HesCU8h2Auguzja4FE4p5Ag1yeDUlIn4sAMVAnRXqD6Lcek+3OemOBnUUh32O4ybEEweFuuVhgKP/cBFrVQvfTTJ77L5+3BEczOMZZ6kmKp3nmo544sBqThpkxYF0t+dU8ULBiMzDrl8vWpldaFRzCaO/BfM0mqp+UM5JhjINPhUSJU62EACtx+I3lhrZ/LBLaiIF/nyeAYjeBFA6gr/slGCErSmQy63kw1Mp7S2tMIRgGAsqllp2Fw9R7jLekxqFLW98L8kYstwXNX/lM7mhinQrFL3J+IK0jCSpwDNfpQrs9Oa6KhmaOwpDXGUASxitPUfyQqMqK31l4p7aPIMEH/142Y5GIag4aJErnmtdVFcIVqTS3+iKZcHJ/uMNJ54QDGqCJemuX5a8R74BM4/uZOywBs0nypOkyiyGAYy6vrYVFcPfMfjtUiaGa1CxSsBioChcZcgZ1U3Io1TYsMGvGW9jgynoi5cTqpzDtA1VAEB3ScgcP2gHp9GcqmQjtKraiggb8RzjyA1d9LfZ3jWQGNoxoQBXxqOyF8l6lsJbPd418QDvJn/NpYyCRXfEi6h7s1taTgfsC5nR2wsPqWIANbTmv3VTjEo2tFp2JSg4T0E+epDNA=
