/**
 * @module types/authentication
 */

export default {
  AUTHENTICATION_REQUESTED: 'AUTHENTICATION_REQUESTED',
  AUTHENTICATION_REQUEST_SUCCEEDED: 'AUTHENTICATION_SUCCEEDED',
  AUTHENTICATION_REQUEST_FAILED: 'AUTHENTICATION_FAILED',
  AUTHENTICATION_REVOKED: 'AUTHENTICATION_REVOKED'
}
