/**
 * @module types/event
 */

export default {
  MY_EVENTS_REQUESTED: 'MY_EVENTS_REQUESTED',
  MY_EVENTS_REQUEST_SUCCEEDED: 'MY_EVENTS_REQUEST_SUCCEEDED',
  MY_EVENTS_REQUEST_FAILED: 'MY_EVENTS_REQUEST_FAILED'
}
