/**
 * @module types/google
 */

export default {
  GOOGLE_OAUTH_URL_REQUESTED: 'GOOGLE_OAUTH_URL_REQUESTED',
  GOOGLE_OAUTH_URL_REQUEST_FAILED: 'GOOGLE_OAUTH_URL_REQUEST_FAILED',
  GOOGLE_OAUTH_URL_REQUEST_SUCCEEDED: 'GOOGLE_OAUTH_URL_REQUEST_SUCCEEDED',

  GOOGLE_TOKENS_REQUESTED: 'GOOGLE_TOKENS_REQUESTED',
  GOOGLE_TOKENS_REQUEST_FAILED: 'GOOGLE_TOKENS_REQUEST_FAILED',
  GOOGLE_TOKENS_REQUEST_SUCCEEDED: 'GOOGLE_TOKENS_REQUEST_SUCCEEDED',

  GOOGLE_CALENDARS_REQUESTED: 'GOOGLE_CALENDARS_REQUESTED',
  GOOGLE_CALENDARS_REQUEST_FAILED: 'GOOGLE_CALENDARS_REQUEST_FAILED',
  GOOGLE_CALENDARS_REQUEST_SUCCEEDED: 'GOOGLE_CALENDARS_REQUEST_SUCCEEDED'
}
