/**
 * @module types/me
 */

export default {
  MY_PROFILE_REQUESTED: 'MY_PROFILE_REQUESTED',
  MY_PROFILE_REQUEST_SUCCEEDED: 'MY_PROFILE_REQUEST_SUCCEEDED',
  MY_PROFILE_REQUEST_FAILED: 'MY_PROFILE_REQUEST_FAILED',

  DESTROY_ME_REQUESTED: 'DESTROY_ME_REQUESTED',
  DESTROY_ME_REQUEST_SUCCEEDED: 'DESTROY_ME_REQUEST_SUCCEEDED',
  DESTROY_ME_REQUEST_FAILED: 'DESTROY_ME_REQUEST_FAILED',

  UPDATE_ME_REQUESTED: 'UPDATE_ME_REQUESTED',
  UPDATE_ME_REQUEST_SUCCEEDED: 'UPDATE_ME_REQUEST_SUCCEEDED',
  UPDATE_ME_REQUEST_FAILED: 'UPDATE_ME_REQUEST_FAILED',

  MY_EVENTS_REQUESTED: 'MY_EVENTS_REQUESTED',
  MY_EVENTS_REQUEST_SUCCEEDED: 'MY_EVENTS_REQUEST_SUCCEEDED',
  MY_EVENTS_REQUEST_FAILED: 'MY_EVENTS_REQUEST_FAILED',

  MY_EVENT_REQUESTED: 'MY_EVENT_REQUESTED',
  MY_EVENT_REQUEST_SUCCEEDED: 'MY_EVENT_REQUEST_SUCCEEDED',
  MY_EVENT_REQUEST_FAILED: 'MY_EVENT_REQUEST_FAILED',

  CREATE_MY_EVENT_REQUESTED: 'CREATE_MY_EVENT_REQUESTED',
  CREATE_MY_EVENT_REQUEST_SUCCEEDED: 'CREATE_MY_EVENT_REQUEST_SUCCEEDED',
  CREATE_MY_EVENT_REQUEST_FAILED: 'CREATE_MY_EVENT_REQUEST_FAILED',

  DESTROY_MY_EVENT_REQUESTED: 'DESTROY_MY_EVENT_REQUESTED',
  DESTROY_MY_EVENT_REQUEST_SUCCEEDED: 'DESTROY_MY_EVENT_REQUEST_SUCCEEDED',
  DESTROY_MY_EVENT_REQUEST_FAILED: 'DESTROY_MY_EVENT_REQUEST_FAILED',

  UPDATE_MY_EVENT_REQUESTED: 'UPDATE_MY_EVENT_REQUESTED',
  UPDATE_MY_EVENT_REQUEST_SUCCEEDED: 'UPDATE_MY_EVENT_REQUEST_SUCCEEDED',
  UPDATE_MY_EVENT_REQUEST_FAILED: 'UPDATE_MY_EVENT_REQUEST_FAILED'
}
