/**
 * @module types/microsoft
 */

export default {
  OAUTH_URL_REQUESTED: 'OAUTH_URL_REQUESTED',
  OAUTH_URL_REQUEST_FAILED: 'OAUTH_URL_REQUEST_FAILED',
  OAUTH_URL_REQUEST_SUCCEEDED: 'OAUTH_URL_REQUEST_SUCCEEDED',

  TOKENS_REQUESTED: 'TOKENS_REQUESTED',
  TOKENS_REQUEST_FAILED: 'TOKENS_REQUEST_FAILED',
  TOKENS_REQUEST_SUCCEEDED: 'TOKENS_REQUEST_SUCCEEDED'
}
