/**
 * @module types/microsoft
 */

export default {
  MICROSOFT_OAUTH_URL_REQUESTED: 'MICROSOFT_OAUTH_URL_REQUESTED',
  MICROSOFT_OAUTH_URL_REQUEST_FAILED: 'MICROSOFT_OAUTH_URL_REQUEST_FAILED',
  MICROSOFT_OAUTH_URL_REQUEST_SUCCEEDED: 'MICROSOFT_OAUTH_URL_REQUEST_SUCCEEDED',

  MICROSOFT_TOKENS_REQUESTED: 'MICROSOFT_TOKENS_REQUESTED',
  MICROSOFT_TOKENS_REQUEST_FAILED: 'MICROSOFT_TOKENS_REQUEST_FAILED',
  MICROSOFT_TOKENS_REQUEST_SUCCEEDED: 'MICROSOFT_TOKENS_REQUEST_SUCCEEDED',

  MICROSOFT_CALENDARS_REQUESTED: 'MICROSOFT_CALENDARS_REQUESTED',
  MICROSOFT_CALENDARS_REQUEST_SUCCEEDED: 'MICROSOFT_CALENDARS_REQUEST_SUCCEEDED',
  MICROSOFT_CALENDARS_REQUEST_FAILED: 'MICROSOFT_CALENDARS_REQUEST_FAILED'
}
