/**
 * @module types/notification
 */

export default {
  NOTIFICATION_PERMISSION_REQUESTED: 'NOTIFICATION_PERMISSION_REQUESTED',
  NOTIFICATION_PERMISSION_GRANTED: 'NOTIFICATION_PERMISSION_GRANTED',
  NOTIFICATION_PERMISSION_DENIED: 'NOTIFICATION_PERMISSION_DENIED',
  NOTIFICATION_STARTED: 'NOTIFICATION_STARTED',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_SUCCEEDED: 'NOTIFICATION_SUCCEEDED'
}
