/**
 * @module types/notification
 */

export default {
  NOTIFICATION_PERMISSION_REQUESTED: 'NOTIFICATION_PERMISSION_REQUESTED',
  NOTIFICATION_PERMISSION_GRANTED: 'NOTIFICATION_PERMISSION_GRANTED',
  NOTIFICATION_PERMISSION_DENIED: 'NOTIFICATION_PERMISSION_DENIED'
}
