/**
 * @module types/notification
 */

export default {
  NOTIFICATION_ENQUEUED: 'NOTIFICATION_ENQUEUED',
  NOTIFICATION_DEQUEUED: 'NOTIFICATION_DEQUEUED',
  NOTIFICATION_CLOSED: 'NOTIFICATION_CLOSED'
}
