/**
 * @module types/sdk
 */

export default {
  SDK_AUTHENTICATION_SET_UP: 'SDK_AUTHENTICATION_SET_UP',
  SDK_AUTHENTICATION_TORN_DOWN: 'SDK_AUTHENTICATION_TORN_DOWN',
  SDK_BASE_PATH_CONFIGURED: 'SDK_BASE_PATH_CONFIGURED'
}
