/**
 * @module types/search
 */

export default {
  SEARCH_REQUESTED: 'SEARCH_REQUESTED',
  SEARCH_REQUEST_SUCCEEDED: 'SEARCH_REQUEST_SUCCEEDED',
  SEARCH_REQUEST_FAILED: 'SEARCH_REQUEST_FAILED',
  SEARCH_CLEARED: 'SEARCH_CLEARED'
}
