/**
 * @module types/socket-io
 */

export default {
  SOCKET_IO_CONNECTION_REQUESTED: 'SOCKET_IO_CONNECTION_REQUESTED',
  SOCKET_IO_CONNECTION_SUCCEEDED: 'SOCKET_IO_CONNECTION_SUCCEEDED',
  SOCKET_IO_CONNECTION_FAILED: 'SOCKET_IO_CONNECTION_FAILED',
  SOCKET_IO_EVENT_HANDLER_MAPPING_STARTED: 'SOCKET_IO_EVENT_HANDLER_MAPPING_STARTED',
  SOCKET_IO_EVENT_HANDLER_MAPPING_SUCCEEDED: 'SOCKET_IO_EVENT_HANDLER_MAPPING_SUCCEEDED',
  SOCKET_IO_EVENT_HANDLER_MAPPING_FAILED: 'SOCKET_IO_EVENT_HANDLER_MAPPING_FAILED'
}
