/**
 * @module types/user
 */

export default {
  CREATE_USER_REQUESTED: 'CREATE_USER_REQUESTED',
  CREATE_USER_REQUEST_SUCCEEDED: 'CREATE_USER_REQUEST_SUCCEEDED',
  CREATE_USER_REQUEST_FAILED: 'CREATE_USER_REQUEST_FAILED',

  CONFIRM_USER_REQUESTED: 'CONFIRM_USER_REQUESTED',
  CONFIRM_USER_REQUEST_SUCCEEDED: 'CONFIRM_USER_REQUEST_SUCCEEDED',
  CONFIRM_USER_REQUEST_FAILED: 'CONFIRM_USER_REQUEST_FAILED',

  FORGOT_PASSWORD_REQUESTED: 'FORGOT_PASSWORD_REQUESTED',
  FORGOT_PASSWORD_REQUEST_SUCCEEDED: 'FORGOT_PASSWORD_REQUEST_SUCCEEDED',
  FORGOT_PASSWORD_REQUEST_FAILED: 'FORGOT_PASSWORD_REQUEST_FAILED',

  RESET_PASSWORD_REQUESTED: 'RESET_PASSWORD_REQUESTED',
  RESET_PASSWORD_REQUEST_FAILED: 'RESET_PASSWORD_REQUEST_FAILED',
  RESET_PASSWORD_REQUEST_SUCCEEDED: 'RESET_PASSWORD_REQUEST_SUCCEEDED'
}
