####################################################################################################
# Format version                                                                                   #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html #
####################################################################################################
AWSTemplateFormatVersion: "2010-09-09"

##########################################################################################################
# Description                                                                                            #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html #
##########################################################################################################
Description: >
  Docket web UI application infrastructure

######################################################################################################
# Metadata                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html #
######################################################################################################
# Metadata:
#   AWS::CloudFormation::Authentication:
#   AWS::CloudFormation::Init:
#   AWS::CloudFormation::Interface:
#   AWS::CloudFormation::Designer:

########################################################################################################
# Conditions                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html #
########################################################################################################
# Conditions:

#######################################################################################################
# Transform                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html #
#######################################################################################################
# Transform:
#   AWS:Serverless:
#   AWS:Include:

######################################################################################################
# Mappings                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html #
######################################################################################################
# Mappings:

########################################################################################################
# Parameters                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html #
########################################################################################################
# Parameters:
#   ReactEnvParameter:
#     AllowedPattern: "[a-z]+"
#     AllowedValues:
#       - "staging"
#       - "production"
#     # ConstraintDescription:
#     # Default:
#     Description: "The environment in which the application will run."
#     # MaxLength:
#     # MaxValue:
#     # MinLength:
#     # MinValue:
#     # NoEcho:
#     Type: "String"
#   ReactAppApiBasePathParameter:
#     # AllowedPattern: "[0-9]+"
#     # AllowedValues:
#     ConstraintDescription: "Must match pattern [0-9]+"
#     Default: 3000
#     Description: "The port that the application will run on."
#     # MaxLength:
#     # MaxValue:
#     # MinLength:
#     # MinValue:
#     # NoEcho:
#     Type: "Number"
#   ReactAppApiVersionParameter:
#     # AllowedPattern:
#     # AllowedValues:
#     # ConstraintDescription:
#     Default: "app:*"
#     Description: "Enables/disables specific debugging namespaces."
#     # MaxLength:
#     # MaxValue:
#     # MinLength:
#     # MinValue:
#     # NoEcho:
#     Type: "String"

#######################################################################################################
# Resources                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html #
#######################################################################################################
Resources:
  CloudFrontToSubdomainARecord:
    Type: "AWS::Route53::RecordSet"
    DependsOn:
      - "CloudFrontDistribution"
    Properties:
      AliasTarget:
        DNSName: !ImportValue "docket-staging:LoadBalancer:DNSName"
        # EvaluateTargetHealth: Boolean
        HostedZoneId: "Z2FDTNDATAQYW2"
      # Comment: String
      # Failover: String
      # GeoLocation:
      #   ContinentCode: String
      #   CountryCode: String
      #   SubdivisionCode: String
      # HealthCheckId: String
      # HostedZoneId: String
      HostedZoneName: "docket.fyi."
      # MultiValueAnswer: Boolean
      Name: "app.staging.docket.fyi."
      # Region: String
      # ResourceRecords:
      #   - String
      # SetIdentifier: String
      # TTL: String
      Type: "A"
      # Weight: Integer
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      # AccelerateConfiguration:
      #   AccelerationStatus: "Enabled" | "Suspended"
      # AccessControl: "Private" | "PublicRead" | "PublicReadWrite" | "AuthenticatedRead" | "LogDeliveryWrite" | "BucketOwnerRead" | "BucketOwnerFullControl" | "AwsExecRead"
      # AnalyticsConfigurations:
      #   - Id: String
      #     Prefix: String
      #     StorageClassAnalysis:
      #       DataExport:
      #         Destination:
      #           BucketAccountId: String
      #           BucketArn: String
      #           Format: String
      #           Prefix: String
      #         OutputSchemaVersion: String
      #     TagFilters:
      #       - Key: String
      #         Value: String
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - ServerSideEncryptionByDefault:
      #         KMSMasterKeyID: String
      #         SSEAlgorithm: String
      BucketName: "app.staging.docket.fyi"
      # CorsConfiguration:
      #   CorsRules:
      #     - AllowedHeaders:
      #         - String
      #       AllowedMethods:
      #         - String
      #       AllowedOrigins:
      #         - String
      #       ExposedHeaders:
      #         - String
      #       Id: String
      #       MaxAge: Integer
      # InventoryConfigurations:
      #   - Destination:
      #       BucketAccountId: String
      #       BucketArn: String
      #       Format: String
      #       Prefix: String
      #     Enabled: Boolean
      #     Id: String
      #     IncludedObjectVersions: String
      #     OptionalFields:
      #       - String
      #     Prefix: String
      #     ScheduleFrequency: String
      # LifecycleConfiguration:
      #   Rules:
      #     - AbortIncompleteMultipartUpload:
      #         DaysAfterInitiation: Integer
      #       ExpirationDate: Timestamp
      #       ExpirationInDays: Integer
      #       Id: String
      #       NoncurrentVersionExpirationInDays: Integer
      #       NoncurrentVersionTransition:
      #         StorageClass: String
      #         TransitionInDays: Integer
      #       NoncurrentVersionTransitions:
      #         - StorageClass: String
      #           TransitionInDays: Integer
      #       Prefix: String
      #       Status: String
      #       TagFilters:
      #         - Key: String
      #           Value: String
      #       Transition:
      #         StorageClass: String
      #         TransitionDate: Timestamp
      #         TransitionInDays: Integer
      #       Transitions:
      #         - StorageClass: String
      #           TransitionDate: Timestamp
      #           TransitionInDays: Integer
      # LoggingConfiguration:
      #   DestinationBucketName: String
      #   LogFilePrefix: String
      # MetricsConfigurations:
      #   - Id: String
      #     Prefix: String
      #     TagFilters:
      #       - Key: String
      #         Value: String
      # NotificationConfiguration:
      #   LambdaConfigurations:
      #     - Event: String
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: String
      #               Value: String
      #       Function: String
      #   QueueConfigurations:
      #     - Event: String
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: String
      #               Value: String
      #       Queue: String
      #   TopicConfigurations:
      #     - Event: String
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: String
      #               Value: String
      #       Topic: String
      # ObjectLockConfiguration:
      #   ObjectLockEnabled: String
      #   Rule:
      #     DefaultRetention:
      #       Days: Integer
      #       Mode: String
      #       Years: Integer
      # ObjectLockEnabled: Boolean
      # PublicAccessBlockConfiguration:
      #   BlockPublicAcls: Boolean
      #   BlockPublicPolicy: Boolean
      #   IgnorePublicAcls: Boolean
      #   RestrictPublicBuckets: Boolean
      # ReplicationConfiguration:
      #   Role: String
      #   Rules:
      #     - Destination:
      #         AccessControlTranslation:
      #           Owner: String
      #         Account: String
      #         Bucket: String
      #         EncryptionConfiguration:
      #           ReplicaKmsKeyID: String
      #         StorageClass: String
      #       Id: String
      #       Prefix: String
      #       SourceSelectionCriteria:
      #         SseKmsEncryptedObjects:
      #           Status: String
      #       Status: String
      # Tags:
      #   - Key: String
      #     Value: String
      # VersioningConfiguration:
      #   Status: String
      WebsiteConfiguration:
        ErrorDocument: "index.html"
        IndexDocument: "index.html"
        # RedirectAllRequestsTo:
        #   HostName: String
        #   Protocol: String
        # RoutingRules:
        #   - RedirectRule:
        #       HostName: String
        #       HttpRedirectCode: String
        #       Protocol: String
        #       ReplaceKeyPrefixWith: String
        #       ReplaceKeyWith: String
        #     RoutingRuleCondition:
        #       HttpErrorCodeReturnedEquals: String
        #       KeyPrefixEquals: String
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "app.staging.docket.fyi"
        # CacheBehaviors:
        #   - AllowedMethods:
        #       - String
        #     CachedMethods:
        #       - String
        #     Compress: Boolean
        #     DefaultTTL: Double
        #     FieldLevelEncryptionId: String
        #     ForwardedValues:
        #       Cookies:
        #         Forward: String
        #         WhitelistedNames:
        #           - String
        #       Headers:
        #         - String
        #       QueryString: Boolean
        #       QueryStringCacheKeys:
        #         - String
        #     LambdaFunctionAssociations:
        #       - EventType: String
        #         LambdaFunctionARN: String
        #     MaxTTL: Double
        #     MinTTL: Double
        #     PathPattern: String
        #     SmoothStreaming: Boolean
        #     TargetOriginId: String
        #     TrustedSigners:
        #       - String
        #     ViewerProtocolPolicy: String
        # Comment: String
        # CustomErrorResponses:
        #   - ErrorCachingMinTTL: Double
        #     ErrorCode: Integer
        #     ResponseCode: Integer
        #     ResponsePagePath: String
        DefaultCacheBehavior:
          # AllowedMethods:
          #   - "GET"
          #   - "HEAD"
          #   - "OPTIONS"
          #   - "PUT"
          #   - "PATCH"
          #   - "POST"
          #   - "DELETE"
          # CachedMethods:
          #   - "GET"
          #   - "HEAD"
          #   - "OPTIONS"
          # Compress: Boolean
          # DefaultTTL: Double
          # FieldLevelEncryptionId: String
          ForwardedValues:
            # Cookies:
            #   Forward: String
            #   WhitelistedNames:
            #     - String
            # Headers:
            #   - String
            QueryString: false
            # QueryStringCacheKeys:
            #   - String
          # LambdaFunctionAssociations:
          #   - EventType: String
          #     LambdaFunctionARN: String
          # MaxTTL: Double
          # MinTTL: Double
          # SmoothStreaming: Boolean
          TargetOriginId: "docket-staging-ui-s3-bucket-origin"
          # TrustedSigners:
          #   - String
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: true
        # HttpVersion: String
        # IPV6Enabled: Boolean
        # Logging:
        #   Bucket: String
        #   IncludeCookies: Boolean
        #   Prefix: String
        Origins:
          -
            # CustomOriginConfig:
            #   HTTPPort: Integer
            #   HTTPSPort: Integer
            #   OriginKeepaliveTimeout: Integer
            #   OriginProtocolPolicy: String
            #   OriginReadTimeout: Integer
            #   OriginSSLProtocols:
            #     - String
            DomainName: !GetAtt "S3Bucket.DomainName"
            Id: "docket-staging-ui-s3-bucket-origin"
            # OriginCustomHeaders:
            #   - HeaderName: String
            #     HeaderValue: String
            # OriginPath: String
            S3OriginConfig:
              OriginAccessIdentity: "" # "origin-access-identity/cloudfront/docket-staging-ui-s3-bucket-origin"
        PriceClass: "PriceClass_100"
        Restrictions:
          GeoRestriction:
            Locations:
              - "US"
            RestrictionType: "whitelist"
        ViewerCertificate:
          # Created manually in the console
          AcmCertificateArn: "arn:aws:acm:us-east-1:763583018324:certificate/28e18184-f185-4828-94ca-b7ee4a169285" # !Ref "UICertificate"
          # CloudFrontDefaultCertificate: true
          # IamCertificateId: String
          # MinimumProtocolVersion: String
          SslSupportMethod: "sni-only"
        # WebACLId: String
      # Tags:
      #   - Key: String
      #     Value: String
  # TODO: The following needs to be created in us-east-1 region because of CloudFront requirements.
  # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html#cfn-cloudfront-distribution-viewercertificate-acmcertificatearn
  # UICertificate:
  #   Type: "AWS::CertificateManager::Certificate"
  #   Properties:
  #     DomainName: "app.staging.docket.fyi"
  #     # DomainValidationOptions:
  #     #   - DomainName: String
  #     #     ValidationDomain: String
  #     # SubjectAlternativeNames:
  #     #   - String
  #     # Tags:
  #     #   - Key: String
  #     #     Value: String
  #     ValidationMethod: "DNS"

#####################################################################################################
# Outputs                                                                                           #
# See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html #
#####################################################################################################
# Outputs:
#   FriendlyName:
#     Description: Information about the value
#     Value: Value to return
#     Export:
#       Name: Value to export
